// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyhmfxeugcxbqwzqhmbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5aG1meGV1Z2N4YnF3enFobWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzYyNTEsImV4cCI6MjA2OTk1MjI1MX0.Cvdtf5v0t1oTMticdjvrXV5zDAJ4CzK24f_WxAXEE_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});